//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;


namespace OpenWorld.Model
{

    

	// nwSystype has a core Name and LongName
	// Can be Listed Found etc
    public class owBaseDataType 
    {
        
        
        //Properties
        public virtual int id { get; protected set; }
        public virtual string Name { get; set; }
        public virtual string LongName { get; set; }

        protected  bool bUseShort;

        public owBaseDataType() {
            if (this.Name == null) { this.Name = ""; }
            if (this.LongName == null) { this.LongName =""; }
        }

        public owBaseDataType(string n, string nl): this()
        {
            if (n.Length > owBaseConst.LEN_SHORT || nl.Length > owBaseConst.LEN_LONG)
            {
                throw new ApplicationException("Name Value too long, truncate Shortname"+n+",LongName"+nl);
            }
            
            this.Name = n.Substring(0, Math.Min(owBaseConst.LEN_SHORT , n.Length ));
            this.LongName = nl.Substring(0, Math.Min(owBaseConst.LEN_LONG , nl.Length ));
            //this.Name = n;
            //this.LongName = nl;
        }

        //Methods
        //overwrite this to get better output
        protected virtual string toStringImpl()
        {
            if (bUseShort) { return this.Name; } else { return this.LongName; }
        }

        protected virtual string ToLongString()
        {
            return "ID " + this.id.ToString() + " Name:" + this.Name + " LongName:" + this.LongName;
        }

        // crap for printing & finding
        public override string ToString()
        {
            return toStringImpl();
        }
       

    }


  
}

